create table produtos
(
    id             bigint generated by default as identity,
    categoria      varchar(255),
    data_cadastro  date,
    desc_descricao varchar(255),
    desc_nome      varchar(255),
    vlr_preco      numeric(19, 2),
    primary key (id)
)
